Ptup/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views
from ptup_utilities.views import RulesSite

handler404 = 'accounts.views.handler404'

urlpatterns = [
    path('admin/', admin.site.urls),

    path('header', views.header, name="header"),
    path('footer', views.footer, name="footer"),

    path('', views.home, name="home"),
    path('site_rules/', RulesSite.as_view(), name="site_rules"),

    # apps
    path('accounts/', include("accounts.urls")),
    path('customers/', include("customers.urls")),
    path('doctors/', include("doctors.urls")),
    path('messages/', include("ptup_messages.urls")),
    path('illness/', include("illness.urls")),
    path('content/', include("healing_content.urls")),
    path('foundation_course/', include("foundation_course.urls")),
    path('followup/', include("followup.urls")),
    path('guide/', include("guide.urls")),

    # PWA
    path('', include('pwa.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ptup_messages/urls.py
from django.urls import path
from . import views

app_name = "ptup_messages"

urlpatterns = [
    path("messages/", views.MessagesView.as_view(), name='messages'),
    path("send_messages/", views.SendMessageView.as_view(), name='send_messages'),
    path("messages/detail/<int:message_id>/", views.DetailMessageView.as_view(), name='messages-detail'),
    path("messages/delete/<int:message_id>/", views.DeleteMessageView.as_view(), name='messages-delete'),

    # Notification
    path("notifications/", views.NotificationView.as_view(), name='notifications'),
]

ptup_messages/models.py
from django.db import models
from accounts.models import User
from django.utils import timezone
from django_quill.fields import QuillField
from django.db.models.aggregates import Count
from random import randint


class Message(models.Model):
    sender = models.ForeignKey(User, on_delete=models.SET_NULL, related_name='sender_messages', null=True,
                               verbose_name='فرستنده ', blank=True)
    receiver = models.ForeignKey(User, on_delete=models.SET_NULL, related_name='receiver_messages', null=True,
                                 verbose_name='گیرنده ')
    subject = models.CharField(max_length=255, null=True, blank=True, default=None, verbose_name='عنوان')
    content = models.TextField(verbose_name='متن پیام ')
    file = models.FileField(verbose_name='فایل پیام', null=True, blank=True)
    is_read = models.BooleanField(verbose_name='خوانده شده/نشده', default=False)
    created_at = models.DateTimeField(default=timezone.now, verbose_name='تاریخ ساخت')

    def __str__(self):
        return f"message {self.id} with sender {self.sender}, receiver {self.receiver}"

    @property
    def get_subject(self):
        return self.subject if self.subject is not None else 'عنوان ندارد'

    class Meta:
        verbose_name = 'پیام'
        verbose_name_plural = 'پیام ها'


class MotivationalMessageManger(models.Manager):
    def random(self):
        count = self.aggregate(count=Count('id'))['count']
        if count > 0:
            random_index = randint(0, count - 1)
            return self.all()[random_index]
        else:
            pass


class MotivationalMessage(models.Model):
    content = models.TextField()

    objects = MotivationalMessageManger()

    def __str__(self):
        return f"motivational message # {self.id}"

    class Meta:
        verbose_name = 'پیام انگیزشی'
        verbose_name_plural = 'پیام های انگیزشی'


class Notification(models.Model):
    sender = models.ForeignKey(User, on_delete=models.SET_NULL, related_name='sender_notification', null=True,
                               verbose_name='فرستنده ', blank=True)
    receiver = models.ForeignKey(User, on_delete=models.SET_NULL, related_name='receiver_notification', null=True,
                                 verbose_name='گیرنده ')
    content = models.TextField()

    class Meta:
        verbose_name = 'اعلان'
        verbose_name_plural = 'اعلان ها'

ptup_messages/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django_quill.forms import QuillFormField


def validate_receiver(text):
    if not text.isnumeric():
        raise ValidationError('فیلد گیرنده فقط باید عدد باشد')


class MessageForm(forms.Form):
    receiver = forms.CharField(validators=[validate_receiver])
    subject = forms.CharField()
    content = QuillFormField()
    file = forms.FileField(widget=forms.FileInput)

ptup_messages/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.utils.decorators import method_decorator
from django.views import View
from django.db.models import Q

from accounts.models import User
from ptup_messages.decorators import is_receiver_or_sender
from ptup_messages.forms import MessageForm
from ptup_messages.models import Message, Notification
from ptup_messages.utility import read_message, get_contacts_doctor, get_contacts_customer
from ptup_utilities.utility import show_custom_errors
from accounts.utilites import phone_number_encryption, phone_number_decryption


@method_decorator(login_required(login_url="accounts:login"), name='dispatch')
class MessagesView(View):
    context = {}

    def get(self, request, *args, **kwargs):
        param = request.GET.get('type', 'inbox')
        if param == "inbox":
            list_messages = Message.objects.filter(receiver=request.user)
            self.context['list_messages'] = list_messages
        elif param == "sent":
            list_messages = Message.objects.filter(sender=request.user)
            self.context['list_messages'] = list_messages
        elif param == "read":
            list_messages = Message.objects.filter(receiver=request.user, is_read=True)
            self.context['list_messages'] = list_messages
        else:
            list_messages = Message.objects.filter(receiver=request.user, is_read=False)
            self.context['list_messages'] = list_messages

        return render(request, 'ptup_messages/messages.html', self.context)


@method_decorator(login_required(login_url="accounts:login"), name='dispatch')
@method_decorator(is_receiver_or_sender, name='dispatch')
class DetailMessageView(View):
    def get(self, request, message_id, *args, **kwargs):
        message = Message.objects.get(id=message_id)

        if request.user == message.receiver:
            read_message(message)

        context = {
            "message": message,
        }
        return render(request, 'ptup_messages/message_detail.html', context)


@method_decorator(login_required(login_url="accounts:login"), name='dispatch')
class DeleteMessageView(View):
    def get(self, request, message_id, *args, **kwargs):
        Message.objects.get(id=message_id).delete()
        messages.success(request, "پیام با موفقیت حذف شد")
        return redirect('ptup_messages:messages')


@method_decorator(login_required(login_url="accounts:login"), name='dispatch')
class SendMessageView(View):
    def get(self, request):
        message_form = MessageForm()

        user = request.user
        context = {}

        if user.role == 1:  # Doctor
            contacts = {}
            customers = get_contacts_doctor(user)

            for customer in customers:
                contacts[customer.nick_name] = phone_number_decryption(phone_number=customer.user.phone)

            context = {
                "message_form": message_form,
                "contacts": contacts,
                "user_role": user.role,
            }
        elif user.role == 2:  # Customer
            contacts = get_contacts_customer(user)
            context = {
                "message_form": message_form,
                "contacts": contacts,
                "user_role": user.role,
            }

        return render(request, 'ptup_messages/send_message.html', context)

    def post(self, request):
        message_form = MessageForm(request.POST, request.FILES)
        if message_form.is_valid():
            phone = message_form.cleaned_data['receiver']
            try:
                receiver = User.objects.filter(
                    Q(phone__exact=phone) | Q(phone__exact=phone_number_encryption(phone_number=phone))).first()
                subject = message_form.cleaned_data['subject']
                content = message_form.cleaned_data['content']
                file = message_form.cleaned_data['file']
                Message.objects.create(
                    sender=request.user,
                    receiver=receiver,
                    subject=subject,
                    content=content,
                    file=file
                )
                messages.success(request, "پیام شما ارسال شد")
                return redirect('ptup_messages:messages')
            except User.DoesNotExist:
                messages.error(request, "کاربر مورد نظر یافت نشد")
                return redirect('ptup_messages:send_messages')
        else:
            error_message = show_custom_errors(message_form.errors)
            messages.error(request, error_message)
            return redirect(request.META.get("HTTP_REFERER"))


# ======================================= Notification ===========================
@method_decorator(login_required(login_url="accounts:login"), name='dispatch')
class NotificationView(View):
    def get(self, request):
        notifications = Notification.objects.filter(receiver=request.user)
        context = {
            "notifications": notifications,
        }
        return render(request, 'ptup_messages/notification.html', context)

ptup_messages/templates/ptup_messages/message_detail.html
{% extends 'shared/_MainLayout.html' %}
{% load static %}
{% load humanize %}

{% block title %}
    پیام
{% endblock %}


{% block content %}

    <div class="content-wrapper" style="min-height: 973.77px;">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>پیام شماره #{{ message.id }}</h1>
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-3">
                        <a href="{% url 'ptup_messages:messages' %}" class="btn btn-primary btn-block mb-3">
                            برگشت به صندوق پیام ها
                        </a>

                        <div class="card">
                            <div class="card-header">
                                <h3 class="card-title" style="float: right">Folders</h3>

                                <div class="card-tools" style="float: left">
                                    <button type="button" class="btn btn-tool" data-card-widget="collapse"><i
                                            class="fas fa-minus"></i>
                                    </button>
                                </div>
                            </div>
                            <div class="card-body p-0">
                                <ul class="nav nav-pills flex-column">
                                    <li class="nav-item">
                                        <a href="{% url 'ptup_messages:send_messages' %}" class="nav-link">
                                            <i class="far fa-paper-plane"></i> ارسال پیام
                                        </a>
                                    </li>
                                    <li class="nav-item active">
                                        <a href="{% url 'ptup_messages:messages' %}" class="nav-link">
                                            <i class="fas fa-inbox"></i> دریافت شده
                                        </a>
                                    </li>
                                    <li class="nav-item">
                                        <a href="/messages/messages/?type=sent" class="nav-link">
                                            <i class="far fa-envelope"></i> ارسال شده
                                        </a>
                                    </li>
                                    <li class="nav-item">
                                        <a href="/messages/messages/?type=read" class="nav-link">
                                            <i class="far fa-check-circle"></i> خوانده شده
                                        </a>
                                    </li>
                                    <li class="nav-item">
                                        <a href="/messages/messages/?type=not_read" class="nav-link">
                                            <i class="far fa-circle"></i>خوانده نشده
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <!-- /.col -->
                    <div class="col-md-9">
                        <div class="card card-primary card-outline">
                            <div class="card-body p-0">
                                <div class="mailbox-read-info">
                                    <h5>{{ message.get_subject }}</h5>
                                    <h6>از: {{ message.sender }}
                                        <span class="mailbox-read-time float-right">
                                            {{ message.created_at }}
                                        </span></h6>
                                </div>
                                <!-- /.mailbox-read-info -->
                                <div class="mailbox-controls with-border text-center">
                                    <div class="btn-group">
                                        <a href="{% url 'ptup_messages:messages-delete' message.id %}"
                                           class="btn btn-default btn-sm" data-toggle="tooltip"
                                           data-container="body" title="Delete">
                                            <i class="far fa-trash-alt"></i></a>
                                    </div>
                                </div>
                                <!-- /.mailbox-controls -->
                                <div class="mailbox-read-message">
                                    <p>
                                        {{ message.content }}
                                    </p>

                                    {% if message.file %}
                                        <hr>
                                        <hr>
                                        <a href="{{ message.file.url }}" download="">فایل پیام</a>
                                    {% endif %}

                                </div>
                            </div>
                        </div>
                        <!-- /.card -->
                    </div>
                    <!-- /.col -->
                </div>
                <!-- /.row -->
            </div>
        </section>
        <!-- /.content -->
    </div>

{% endblock %}

ptup_messages/templates/ptup_messages/messages.html
{% extends 'shared/_MainLayout.html' %}
{% load static %}
{% load humanize %}

{% block title %}
    پیام ها
{% endblock %}

{% block content %}

    <div class="content-wrapper" style="min-height: 973.77px;">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>لیست پیام ها</h1>
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="row">
                <div class="col-md-3">

                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title" style="float: right">Folders</h3>

                            <div class="card-tools" style="float: left">
                                <button type="button" class="btn btn-tool" data-card-widget="collapse"><i
                                        class="fas fa-minus"></i>
                                </button>
                            </div>
                        </div>
                        <div class="card-body p-0">
                            <ul class="nav nav-pills flex-column">
                                <li class="nav-item">
                                    <a href="{% url 'ptup_messages:send_messages' %}" class="nav-link">
                                        <i class="far fa-paper-plane"></i> ارسال پیام
                                    </a>
                                </li>
                                <li class="nav-item active">
                                    <a href="{% url 'ptup_messages:messages' %}" class="nav-link">
                                        <i class="fas fa-inbox"></i> دریافت شده
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="/messages/messages/?type=sent" class="nav-link">
                                        <i class="far fa-envelope"></i> ارسال شده
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="/messages/messages/?type=read" class="nav-link">
                                        <i class="far fa-check-circle"></i> خوانده شده
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="/messages/messages/?type=not_read" class="nav-link">
                                        <i class="far fa-circle"></i>خوانده نشده
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
                <!-- /.col -->
                <div class="col-md-9">
                    <div class="card card-primary card-outline">
                        <div class="card-header">
                            <h3 class="card-title" style="float: right">پیام ها</h3>

                        </div>

                        <div class="card-body p-0">
                            <div class="table-responsive mailbox-messages">
                                <table class="table table-hover table-striped">
                                    <tbody>
                                    {% for message in list_messages %}
                                        <tr>
                                            <td>
                                                <div class="icheck-primary">
                                                    <input type="checkbox" value="" id="check1">
                                                    <label for="check1"></label>
                                                </div>
                                            </td>
                                            <td class="mailbox-name">
                                                <a href="{% url 'ptup_messages:messages-detail' message.id %}">{{ message.sender }}</a>
                                            </td>
                                            <td class="mailbox-subject">
                                                {{ message.subject|truncatewords:6 }}
                                            </td>
                                            <td class="mailbox-attachment"></td>
                                            <td class="mailbox-date">{{ message.created_at|naturaltime }}</td>
                                        </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>

{% endblock %}


{% block footer_ref %}

{% endblock %}

ptup_messages/templates/ptup_messages/notification.html
{% extends 'shared/_MainLayout.html' %}

{% block title %}
    اعلان ها
{% endblock %}

{% block content %}
    <div class="content-wrapper" style="min-height: 1016.95px;">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>لیست اعلان ها</h1>
                    </div>
                </div>
            </div>
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-6">

                        <div class="card">
                            <div class="card-body p-0">
                                <table class="table table-condensed">
                                    <thead>
                                    <tr>
                                        <th style="width: 10px">#</th>
                                        <th>توضیحات</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% for notification in notifications %}
                                        <tr>
                                            <td>{{ forloop.counter }}.</td>
                                            <td>
                                                {{ notification.content }}
                                            </td>
                                        </tr>
                                    {% endfor %}

                                    </tbody>
                                </table>
                            </div>
                            <!-- /.card-body -->
                        </div>

                    </div>
                </div>
            </div>
        </section>
    </div>
{% endblock %}