Ptup/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views
from ptup_utilities.views import RulesSite

handler404 = 'accounts.views.handler404'

urlpatterns = [
    path('admin/', admin.site.urls),

    path('header', views.header, name="header"),
    path('footer', views.footer, name="footer"),

    path('', views.home, name="home"),
    path('site_rules/', RulesSite.as_view(), name="site_rules"),

    # apps
    path('accounts/', include("accounts.urls")),
    path('customers/', include("customers.urls")),
    path('doctors/', include("doctors.urls")),
    path('messages/', include("ptup_messages.urls")),
    path('illness/', include("illness.urls")),
    path('content/', include("healing_content.urls")),
    path('foundation_course/', include("foundation_course.urls")),
    path('followup/', include("followup.urls")),
    path('guide/', include("guide.urls")),

    # PWA
    path('', include('pwa.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

customers/urls.py
from django.urls import path
from . import views

app_name = 'customers'

urlpatterns = [
    path('completion_information_customer/', views.CompletionInformationCostumer.as_view(),
         name='completion_information_customer'),

    path('filter_customer/', views.FilterCustomer.as_view(), name="filter_customer"),

    path('customer/<int:customer_id>/detail/', views.CustomerInformationDetail.as_view(), name="customer_detail"),

    path('determining_customer_illness/<int:customer_id>/', views.DeterminingCustomerIllness.as_view(),
         name="determining_customer_illness"),

    path('operation_choice_illness_customer/<int:customer_id>/<int:illness_id>/',
         views.OperationChoiceIllnessCustomer.as_view(),
         name="operation_choice_illness_customer"),

    path('permission_start_treatment/', views.PermissionStartTreatmentCustomer.as_view(),
         name='permission_start_treatment'),

    # --------------------------------------------------

    path('healing_period_each_week/', views.healing_content_each_week, name='healing_period_each_week'),

    path('practices_each_week/<int:practice_each_week_id>/', views.practice_each_week,
         name='practices_each_week'),

    path('questionnaires_weekly/', views.questionnaires_weekly, name='questionnaires_weekly'),

    path('healing_content_map/', views.HealingContentMap.as_view(), name="healing_content_map"),

    path('completion_practice/', views.CompletionPractice.as_view(), name='completion_practice'),

    path('foundation_course_customer/', views.FoundationCourseCustomer.as_view(), name='foundation_course_customer'),

]

healing_content/urls.py
from django.urls import path

from . import views

app_name = "healing_content"

urlpatterns = [
    path('day_feedback_detail/<int:customer_id>/<int:healing_week_id>/', views.DayFeedbackView.as_view(),
         name="day_feedback_detail"),

    # path('show_feedback/<int:healing_week_id>/', views.ShowFeedbackByCustomerView.as_view(), name="show_feedback"),

    path('create_feedback/', views.CreateFeedbackView.as_view(), name="create_feedback"),

    # Questionnaire Weekly
    path('questionnaire_weekly/<int:questionnaire_id>/<int:healing_week_id>/', views.QuestionnaireWeeklyView.as_view(),
         name="questionnaire_weekly"),

    path('complate_questionnaire_weekly/', views.CompleteQuestionnaireWeeklyByCustomer.as_view(),
         name="complate_questionnaire_weekly"),
]

healing_content/forms.py
from django import forms


class PracticeAnswerForm(forms.Form):
    healing_day = forms.IntegerField()
    content = forms.CharField(widget=forms.Textarea, required=False)
    file = forms.FileField(widget=forms.FileInput, required=False)

    def clean(self):
        cleaned_data = super().clean()
        content = cleaned_data.get('content')
        file = cleaned_data.get('file')

        if not content and not file:
            raise forms.ValidationError("فیلد توضیحات یا فایل وارد نشده است")

        return cleaned_data


class DayFeedbackForm(forms.Form):
    answer_practice_id = forms.IntegerField()
    subject = forms.CharField()
    content = forms.CharField(widget=forms.TextInput)

healing_content/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.views import View
from django.utils.decorators import method_decorator
from django.contrib import messages
from django.db import transaction

from customers.models import Customer
from customers.tasks.customer_activity_history import create_activity_history
from customers.tasks.customers import increase_week_of_healing_period, check_last_day_healing_period
from foundation_course.tasks.questionnaire import get_list_answer_questionnaire
from foundation_course.utility import calculate_score_each_questionnaire_weekly
from healing_content.forms import DayFeedbackForm
from healing_content.models import DayFeedback, QuestionnaireWeek, QuestionWeek, \
    QuestionnaireWeekAnswer, QuestionnaireWeekAnswerDetail, AnswerPractice


@method_decorator(login_required(login_url="accounts:login"), name='dispatch')
class DayFeedbackView(View):
    def get(self, request, customer_id, healing_week_id, *args, **kwargs):
        user_role = request.user.role
        try:
            customer = Customer.objects.get(id=customer_id)
            answer_practice_list = AnswerPractice.objects.filter(customer=customer, healing_week_id=healing_week_id)

            context = {
                "user_role": user_role,
                "answer_practice_list": answer_practice_list,
            }
            return render(request, 'healing_content/day_feedback_detail.html', context)
        except Customer.DoesNotExist:
            pass


@method_decorator(login_required(login_url="accounts:login"), name='dispatch')
class CreateFeedbackView(View):
    def post(self, request, *args, **kwargs):
        form = DayFeedbackForm(request.POST)
        if form.is_valid():
            answer_practice_id = form.cleaned_data.get('answer_practice_id')
            subject = form.cleaned_data.get('subject')
            content = form.cleaned_data.get('content')
            with transaction.atomic():
                try:
                    day_feedback = DayFeedback.objects.get(practice_answer_id=answer_practice_id)

                    day_feedback.subject = subject
                    day_feedback.content = content
                    day_feedback.save()
                    messages.success(request, 'بازخورد بروزرسانی شد')
                    return redirect(request.META.get("HTTP_REFERER"))

                except DayFeedback.DoesNotExist:
                    DayFeedback.objects.create(
                        practice_answer_id=answer_practice_id,
                        doctor=request.user.doctor,
                        subject=subject,
                        content=content
                    )
                    messages.success(request, 'بازخورد ثبت شد')
                    return redirect(request.META.get("HTTP_REFERER"))
        else:
            messages.error(request, f"{form.errors.as_text()}")
            return redirect(request.META.get("HTTP_REFERER"))


# =============================== Questionnaire Weekly ========================
@method_decorator(login_required(login_url="accounts:login"), name='dispatch')
class QuestionnaireWeeklyView(View):
    def get(self, request, questionnaire_id, healing_week_id, *args, **kwargs):
        questionnaire_week = QuestionnaireWeek.objects.get(id=questionnaire_id)

        number_of_option = "".join([str(i) for i in range(1, questionnaire_week.number_of_options + 1)])

        questions = QuestionWeek.objects.filter(questionnaire_week=questionnaire_week).order_by('row')

        context = {
            "healing_week_id": healing_week_id,
            "questionnaire": questionnaire_week,
            "number_of_option": number_of_option,
            "questions": questions,
            "questions_count": questions.count(),
        }
        return render(request, 'healing_content/questionnaire_weekly_detail.html', context)


@method_decorator(login_required(login_url="accounts:login"), name='dispatch')
class CompleteQuestionnaireWeeklyByCustomer(View):
    def post(self, request):
        if request.method == "POST":
            customer = request.user.customer
            healing_week_id = request.POST['healing_week_id']
            questionnaire_id = request.POST['questionnaire_id']
            questions_count = request.POST['questions_count']
            questionnaire = QuestionnaireWeek.objects.get(id=questionnaire_id)
            with transaction.atomic():

                selected_answers = get_list_answer_questionnaire(request.POST.items())

                if int(questions_count) == len(selected_answers.keys()):
                    questionnaire_answer = QuestionnaireWeekAnswer.objects.create(
                        questionnaire_week=questionnaire,
                        customer=customer,
                        healing_week_id=healing_week_id
                    )

                    objects_to_create = []
                    for key, value in selected_answers.items():
                        objects_to_create.append(QuestionnaireWeekAnswerDetail(
                            questionnaire_week=questionnaire_answer,
                            question_week_id=key,
                            question_option_week_id=value
                        ))

                    answers_list = QuestionnaireWeekAnswerDetail.objects.bulk_create(objects_to_create)

                    calculate_score_each_questionnaire_weekly(questionnaire_answer, answers_list)

                    # TODO: Increase the week number of the user's healing period
                    increase_week_of_healing_period(request, customer)

                    # TODO: Checking whether it is the last day of the Healing period or not
                    check_last_day_healing_period(request, healing_week_id, customer)

                    # TODO: Register activity history
                    create_activity_history(customer.id, 'تکمیل پرسشنامه هفتگی',
                                            f'تکمیل پرسشنامه هفتگی : {questionnaire_answer.questionnaire_week.__str__()}')

                    return redirect('customers:healing_period_each_week')
                else:
                    messages.error(request, "لطفا پرسشنامه را تکمیل کنید")
                    return redirect(request.META.get("HTTP_REFERER"))

healing_content/templates/healing_content/completion_practice_each_week.html
{% extends "shared/_MainLayout.html" %}
{% load static %}

{% block title %}
    تمرین ها
{% endblock %}

{% block content %}
    <div class="content-wrapper" style="min-height: 1232.89px;">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>انجام تمرین های هفته {{ week }} ام</h1>
                    </div>
                </div>
            </div>
        </section>

        <section class="content">
            <div class="container-fluid">

                {% for day, practices_in_day in practices.items %}
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="card">
                                <div class="card-header bg-primary">
                                    <h3>تمرین های روز {{ day }}</h3>
                                </div>
                                {% for practice, practice_items in practices_in_day.items %}
                                    <div class="card-body">
                                        <div class="card-body bg-gray-light">
                                            <h6>توضیحات : {{ practice.description }}</h6>
                                            <hr>
                                            <h6>فایل های تمرین :</h6>
                                            <ul>
                                                {% for key, contents in practice_items.items %}
                                                    {% if key == "contents" %}
                                                        {% for content in contents %}
                                                            <li>
                                                                {% if content.type == "MEDIA" %}
                                                                    <a href="{{ content.file.url }}" download><h6>
                                                                        ویدیو : {{ content.title }}</h6></a>
                                                                {% elif content.type == "VOICE" %}
                                                                    <a href="{{ content.file.url }}" download><h6>
                                                                        صدا : {{ content.title }}</h6></a>
                                                                {% elif content.type == "FILE" %}
                                                                    <a href="{{ content.file.url }}" download><h6>
                                                                        فایل : {{ content.title }}</h6></a>
                                                                {% endif %}
                                                            </li>
                                                        {% endfor %}
                                                    {% endif %}
                                                {% endfor %}
                                            </ul>
                                        </div>
                                        <hr>
                                        <div class="card-body">
                                            <form action="{% url 'customers:completion_practice' %}" method="POST">
                                                {% csrf_token %}
                                                <input type="hidden" name="healing_week_id"
                                                       value="{{ healing_week_id }}">
                                                {% for key, questions in practice_items.items %}
                                                    {% if key == "questions" %}
                                                        {% for question in questions %}
                                                            <div class="card">
                                                                <div class="card-header">{{ question.row }}. {{ question.text }}</div>
                                                                <div class="card-body">
                                                                    <div class="form-group">
                                                                        <label for="">متن جواب : </label>
                                                                        {% load answer_customer_filter %}
                                                                        <h2>{{ question.answer_practice.all|get_answer_customer:request.user }}</h2>
                                                                        <input type="text" class="form-control"
                                                                               name="answer{{ question.id }}"
                                                                               value="{{ question.answer_practice.all|get_answer_customer:request.user.customer }}">
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        {% endfor %}
                                                    {% endif %}
                                                {% endfor %}
                                                <button type="submit" class="btn btn-block btn-primary">ثبت</button>
                                            </form>
                                        </div>
                                    </div>
                                {% endfor %}

                            </div>
                        </div>
                    </div>
                {% endfor %}




{#                {% if questionnaires_weekly is not None %}#}
{#                    <div class="row">#}
{#                        <div class="col-lg-12">#}
{#                            <div class="card">#}
{#                                <div class="card-header">#}
{#                                    <h3>پرسشنامه های هفتگی</h3>#}
{#                                </div>#}
{#                                <div class="card-body d-flex flex-wrap">#}
{#                                    {% for questionnaire in questionnaires_weekly %}#}
{#                                        <div class="col-md-3 col-sm-6 col-12">#}
{#                                            <div class="info-box bg-info">#}
{#                                                <span class="info-box-icon"><i class="far fa-bookmark"></i></span>#}
{##}
{#                                                <div class="info-box-content">#}
{#                                                    <a href="/content/questionnaire_weekly/{{ questionnaire.id }}/{{ healing_week_id }}/"#}
{#                                                       style="color: white">#}
{#                                                        <h5>{{ questionnaire.title }}</h5></a>#}
{#                                                </div>#}
{#                                            </div>#}
{#                                        </div>#}
{#                                    {% endfor %}#}
{#                                </div>#}
{#                            </div>#}
{#                        </div>#}
{#                    </div>#}
{#                {% endif %}#}

            </div>
        </section>

    </div>
{% endblock %}

healing_content/templates/healing_content/day_feedback_detail.html
{% extends "shared/_MainLayout.html" %}

{% block title %}
    جزییات تمرین
{% endblock %}


{% block content %}
    <div class="content-wrapper" style="min-height: 1232.89px;">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>{{ disease_information.healing_period }}</h1>
                    </div>
                </div>
            </div>
        </section>

        <section class="content">
            <div class="container-fluid">
                <div class="row mt-3">

                    <div class="col-lg-12">
                        <div class="card">
                            <div class="card-header bg-primary">
                                <h5>پاسخ بیمار به تمرین ها در این هفته</h5>
                            </div>
                            <div class="card-body ">

                                {% for answer_practice in answer_practice_list %}
                                    <div class="card bg-gray-light">
                                        <div class="card-header">
                                            <h5>{{ forloop.counter }}
                                                - {{ answer_practice.question_practice.text }}</h5>
                                        </div>
                                        <div class="card-body">
                                            <div class="row">
                                                <div class="col-lg-6">
                                                    <span class="text-bold">جواب بیمار : </span> {{ answer_practice.answer }}
                                                </div>
                                                <div class="col-lg-6">

                                                    {% if user_role == 1 %}
                                                        <div class="card">
                                                            <div class="card-header bg-primary">
                                                                <h5>ثبت بازخورد</h5>
                                                            </div>
                                                            <form action="{% url 'healing_content:create_feedback' %}"
                                                                  method="POST">
                                                                {% csrf_token %}
                                                                <input type="hidden" name="answer_practice_id"
                                                                       value="{{ answer_practice.id }}">
                                                                <div class="card-body">
                                                                    <div class="form-group">
                                                                        <label for="subject">عنوان :</label>
                                                                        <input type="text" class="form-control"
                                                                               id="subject"
                                                                               name="subject"
                                                                               value="{{ answer_practice.dey_feedbacks.all.first.subject }}">
                                                                    </div>
                                                                    <div class="form-group">
                                                                        <label for="content">توضیحات :</label>
                                                                        <textarea name="content" class="form-control"
                                                                                  id="content" cols="15"
                                                                                  rows="10">{{ answer_practice.dey_feedbacks.all.first.content }}</textarea>
                                                                    </div>
                                                                </div>
                                                                <button type="submit" class="btn btn-block btn-primary">
                                                                    ثبت
                                                                </button>

                                                            </form>
                                                        </div>

                                                    {% elif user_role == 2 %}
                                                        <div class="card">
                                                            <div class="card-header">
                                                                عنوان بازخورد : {{ answer_practice.dey_feedbacks.all.first.subject }}
                                                            </div>
                                                            <div class="card-body">
                                                                <p><span class="text-bold">توضیحات</span>
                                                                    : {{ answer_practice.dey_feedbacks.all.first.content }}
                                                                </p>
                                                            </div>
                                                        </div>
                                                    {% endif %}
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                {% endfor %}


                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </section>

    </div>
{% endblock %}

healing_content/templates/healing_content/healing_period_each_week.html
{% extends "shared/_MainLayout.html" %}
{% load static %}

{% block title %}
    دوره درمان
{% endblock %}

{% block content %}
    <div class="content-wrapper" style="min-height: 1232.89px;">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>{{ disease_information.healing_period }}</h1>
                    </div>
                </div>
            </div>
        </section>

        <section class="content">
            <div class="container-fluid">
                <div class="row mt-3">

                    <div class="col-lg-12">
                        <div class="card">
                            <div class="card-header bg-primary">
                                <h5>{{ disease_information.healing_period }}</h5>
                            </div>
                            <div class="card-body ">
                                <div class="d-flex my-1">
                                    <span><i class="fas fa-plus"></i></span>
                                    <h6 class="mx-2">
                                        عنوان بیماری : {{ disease_information.illness.title }}
                                    </h6>
                                </div>
                                <div class="d-flex my-1">
                                    <span><i class="fas fa-plus"></i></span>
                                    <h6 class="mx-2">
                                        توضیحات بیماری : {{ disease_information.illness.description }}
                                    </h6>
                                </div>
                                <div class="d-flex my-1">
                                    <span><i class="fas fa-plus"></i></span><h6 class="mx-2">مدت زمان دوره درمان
                                    : {{ disease_information.healing_period.duration_of_treatment }}
                                    هفته</h6>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>


                <div class="row mt-3">
                    <div class="col-lg-12">
                        <div class="card">
                            <div class="card-header bg-primary">
                                <h5>محتوای درمانی هفته {{ week }} ام</h5>
                            </div>

                            <div class="row">
                                {% for content in contents %}
                                    <div class="col-lg-4 my-3">
                                        {% if content.type == 'MEDIA' %}
                                            <div class="card">
                                                <div class="card-header text-center">
                                                    <h4>ویدیو</h4>
                                                </div>
                                                <div class="card-body">
                                                    <video src="{{ content.file.url }}" width="100%"
                                                           height="100%" controls></video>
                                                </div>
                                            </div>
                                        {% elif content.type == "VOICE" %}
                                            <div class="card">
                                                <div class="card-header text-center">
                                                    <h4>صدا</h4>
                                                </div>
                                                <div class="card-body">
                                                    <audio src="{{ content.file.url }}" controls></audio>
                                                </div>
                                            </div>
                                        {% else %}
                                            <div class="card">
                                                <div class="card-header text-center">
                                                    <h4>فایل</h4>
                                                </div>
                                                <div class="card-body d-flex">
                                                    <div>
                                                        {{ content.pdf_preview }}
                                                    </div>
                                                    <a class="text-center" href="{{ content.file.url }}"
                                                       style="margin: 10px auto; color: black">
                                                        <img src="{% static 'dist/img/pdf-icone.png' %}"
                                                             alt="pdf-icon"
                                                             width="100px" height="100px">
                                                    </a>
                                                </div>
                                            </div>
                                        {% endif %}
                                    </div>
                                {% endfor %}
                            </div>

                            <div class="card-footer">
                                <a href="{% url 'customers:practices_each_week' healing_week.id %}"
                                   class="btn btn-primary">
                                    انجام تمرین های هفته {{ week }} ام
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>

    </div>
{% endblock %}