Ptup/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views
from ptup_utilities.views import RulesSite

handler404 = 'accounts.views.handler404'

urlpatterns = [
    path('admin/', admin.site.urls),

    path('header', views.header, name="header"),
    path('footer', views.footer, name="footer"),

    path('', views.home, name="home"),
    path('site_rules/', RulesSite.as_view(), name="site_rules"),

    # apps
    path('accounts/', include("accounts.urls")),
    path('customers/', include("customers.urls")),
    path('doctors/', include("doctors.urls")),
    path('messages/', include("ptup_messages.urls")),
    path('illness/', include("illness.urls")),
    path('content/', include("healing_content.urls")),
    path('foundation_course/', include("foundation_course.urls")),
    path('followup/', include("followup.urls")),
    path('guide/', include("guide.urls")),

    # PWA
    path('', include('pwa.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

customers/urls.py
from django.urls import path
from . import views

app_name = 'customers'

urlpatterns = [
    path('completion_information_customer/', views.CompletionInformationCostumer.as_view(),
         name='completion_information_customer'),

    path('filter_customer/', views.FilterCustomer.as_view(), name="filter_customer"),

    path('customer/<int:customer_id>/detail/', views.CustomerInformationDetail.as_view(), name="customer_detail"),

    path('determining_customer_illness/<int:customer_id>/', views.DeterminingCustomerIllness.as_view(),
         name="determining_customer_illness"),

    path('operation_choice_illness_customer/<int:customer_id>/<int:illness_id>/',
         views.OperationChoiceIllnessCustomer.as_view(),
         name="operation_choice_illness_customer"),

    path('permission_start_treatment/', views.PermissionStartTreatmentCustomer.as_view(),
         name='permission_start_treatment'),

    # --------------------------------------------------

    path('healing_period_each_week/', views.healing_content_each_week, name='healing_period_each_week'),

    path('practices_each_week/<int:practice_each_week_id>/', views.practice_each_week,
         name='practices_each_week'),

    path('questionnaires_weekly/', views.questionnaires_weekly, name='questionnaires_weekly'),

    path('healing_content_map/', views.HealingContentMap.as_view(), name="healing_content_map"),

    path('completion_practice/', views.CompletionPractice.as_view(), name='completion_practice'),

    path('foundation_course_customer/', views.FoundationCourseCustomer.as_view(), name='foundation_course_customer'),

]

ptup_messages/urls.py
from django.urls import path
from . import views

app_name = "ptup_messages"

urlpatterns = [
    path("messages/", views.MessagesView.as_view(), name='messages'),
    path("send_messages/", views.SendMessageView.as_view(), name='send_messages'),
    path("messages/detail/<int:message_id>/", views.DetailMessageView.as_view(), name='messages-detail'),
    path("messages/delete/<int:message_id>/", views.DeleteMessageView.as_view(), name='messages-delete'),

    # Notification
    path("notifications/", views.NotificationView.as_view(), name='notifications'),
]

doctors/models.py
from django.db import models
from django.utils import timezone

from accounts.models import User
from datetime import datetime


class GenderChoices(models.IntegerChoices):
    MEN = 1, 'مرد'
    WOMEN = 2, 'زن'


class ApproachUsedTreatment(models.Model):
    title = models.CharField(max_length=255, verbose_name='عنوان ')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'رویکرد درمان'
        verbose_name_plural = 'رویکرد های درمان'


class Doctor(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name="کاربر")
    first_name = models.CharField(max_length=255, verbose_name='نام')
    last_name = models.CharField(max_length=255, verbose_name='نام خانوادگی')
    email = models.EmailField(verbose_name='ایمیل')
    gender = models.SmallIntegerField(choices=GenderChoices.choices, default=GenderChoices.MEN, verbose_name='جنسیت')
    home_address = models.CharField(max_length=550, verbose_name='آدرس خانه')
    clinic_address = models.CharField(max_length=550, verbose_name='آدرس کلنیک')
    home_number = models.CharField(max_length=30, verbose_name='شماره تلفن خانه')
    national_code = models.CharField(max_length=20, verbose_name='کد ملی')
    psychology_license_number = models.CharField(max_length=100, verbose_name='شماره پروانه نظام روانشناسی')
    university_graduate = models.CharField(max_length=255, verbose_name='دانشگاه فارغ التحصیلی')
    field_of_study_bachelor = models.CharField(max_length=255, verbose_name='رشته تحصیلی لیسانس')
    field_of_study_residence = models.CharField(max_length=255, verbose_name='رشته تحصیلی ارشد')
    city_of_residence = models.CharField(max_length=255, verbose_name='شهر محل اقامت')
    treatment_history = models.PositiveSmallIntegerField(default=0, verbose_name='سابقه درمانی')
    approach_used_treatment = models.ForeignKey(ApproachUsedTreatment, on_delete=models.SET_NULL, null=True, blank=True,
                                                verbose_name='رویکرد مورد استفاده در درمان ')
    image_profile = models.ImageField(upload_to='files/image_profile_doctors/', verbose_name='عکس')
    is_verify = models.BooleanField(default=False, verbose_name='اجازه شروع فعالیت')

    def __str__(self):
        return f"دکتر {self.first_name} {self.last_name}"

    @property
    def get_full_name(self):
        return self.__str__()

    @property
    def get_image_profile_url(self):
        image_profile_url = self.image_profile.url
        if image_profile_url:
            return image_profile_url
        return ''

    @property
    def get_gender(self):
        return 'مرد' if self.gender == 1 else 'زن'

    class Meta:
        verbose_name = 'دکتر'
        verbose_name_plural = 'دکترها'


class IdentificationDocument(models.Model):
    doctor = models.ForeignKey(Doctor, on_delete=models.CASCADE, verbose_name='دکتر ')
    title = models.CharField(max_length=255, verbose_name='عنوان فایل ')
    file = models.FileField(verbose_name='فایل ', upload_to='files/identification_document/')
    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f"{self.title} : {self.doctor}"

    @property
    def get_file_size_as_str(self):
        file_size_bytes = self.file.size
        # Define the size units and their corresponding labels
        size_units = ['B', 'KB', 'MB', 'GB', 'TB', 'PB']
        index = 0

        while file_size_bytes >= 1024 and index < len(size_units) - 1:
            file_size_bytes /= 1024
            index += 1

        return f"{file_size_bytes:.2f} {size_units[index]}"

    class Meta:
        verbose_name = 'مدرک شناسایی'
        verbose_name_plural = 'مدارک شناسایی دکترها'

templates/home_customer.html
{% extends 'shared/_MainLayout.html' %}
{% load static %}


{% block title %}
    صفحه اصلی
{% endblock %}

{% block content %}
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <div class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1 class="m-0 text-dark">داشبورد</h1>
                    </div>
                </div>
            </div>
        </div>
        <!-- /.content-header -->

        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">


                <div class="row">
                    <div class="col-12">
                        <!-- Default box -->
                        <div class="card">
                            <div class="card-header">
                                <h3 class="card-title" style="float: right">پیام انگیزشی</h3>

                                <div class="card-tools" style="float: left">
                                    <button type="button" class="btn btn-tool" data-card-widget="collapse"
                                            data-toggle="tooltip" title="Collapse">
                                        <i class="fas fa-minus"></i></button>
                                    <button type="button" class="btn btn-tool" data-card-widget="remove"
                                            data-toggle="tooltip" title="Remove">
                                        <i class="fas fa-times"></i></button>
                                </div>
                            </div>
                            <div class="card-body">
                                {{ motivational_message.content }}
                            </div>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-3 col-sm-6 col-12">
                        <div class="info-box">
                            <span class="info-box-icon bg-info">
                                <a href="{% url 'ptup_messages:messages' %}">
                                    <i class="far fa-envelope"></i>
                                </a>
                            </span>

                            <div class="info-box-content">
                                <span class="info-box-text">پیام ها</span>
                                <span class="info-box-number">{{ messages_count }}</span>
                            </div>
                        </div>
                    </div>

                    <div class="col-md-3 col-sm-6 col-12">
                        <div class="info-box">
                            <span class="info-box-icon bg-success">
                                <a href="{% url 'ptup_messages:notifications' %}">
                                    <i class="nav-icon far fa-bell"></i>
                                </a>
                            </span>

                            <div class="info-box-content">
                                <span class="info-box-text">اعلان ها</span>
                                <span class="info-box-number">{{ notification_count }}</span>
                            </div>
                        </div>
                    </div>

                    <div class="col-md-3 col-sm-6 col-12">
                        <div class="info-box">
                            <span class="info-box-icon bg-warning">
                                <a href="{% url 'customers:healing_content_map' %}">
                                    <i class="far fa-copy"></i>
                                </a>
                            </span>

                            <div class="info-box-content">
                                <span class="info-box-text">پرونده درمانی خودم</span>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </section>
    </div>

{% endblock %}

templates/home_doctor.html
{% extends 'shared/_MainLayout.html' %}
{% load static %}


{% block title %}
    صفحه اصلی
{% endblock %}

{% block content %}
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <div class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1 class="m-0 text-dark">داشبورد</h1>
                    </div>
                </div>
            </div>
        </div>
        <!-- /.content-header -->

        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-3 col-6">
                        <!-- small box -->
                        <div class="small-box bg-warning">
                            <div class="inner">
                                <h3>{{ count_customers }}</h3>

                                <p>تعداد بیماران</p>
                            </div>
                            <div class="icon">
                                <i class="ion ion-person-add"></i>
                            </div>
                            <a href="{% url 'doctors:list_customers_requested' %}" class="small-box-footer">More info <i
                                    class="fas fa-arrow-circle-right"></i></a>
                        </div>
                    </div>
                    <!-- ./col -->
                    <div class="col-lg-3 col-6">
                        <!-- small box -->
                        <div class="small-box bg-success">
                            <div class="inner">
                                <h3>{{ count_messages_not_read }}</h3>

                                <p>تعداد پیام های جدید</p>
                            </div>
                            <div class="icon">
                                <i class="ion ion-stats-bars"></i>
                            </div>
                            <a href="{% url 'ptup_messages:messages' %}" class="small-box-footer">More info <i
                                    class="fas fa-arrow-circle-right"></i></a>
                        </div>
                    </div>
                </div>


                <div class="row">
                    <section class="content col-lg-12">
                        <div class="card">
                            <div class="card-header">
                                <h3 class="card-title" style="float: right">
                                    لیست بیماران دوره مقدماتی
                                </h3>

                                <div class="card-tools" style="float: left">
                                    <button type="button" class="btn btn-tool" data-card-widget="collapse"
                                            data-toggle="tooltip" title="Collapse">
                                        <i class="fas fa-minus"></i></button>
                                    <button type="button" class="btn btn-tool" data-card-widget="remove"
                                            data-toggle="tooltip" title="Remove">
                                        <i class="fas fa-times"></i></button>
                                </div>
                            </div>

                            <div class="card-body p-0" style="display: block;">
                                <table class="table table-striped projects">
                                    <thead>
                                    <tr>
                                        <th style="width: 1%">
                                            #
                                        </th>
                                        <th style="width: 20%">
                                            نام مستعار
                                        </th>
                                        <th style="width: 30%">
                                            سن
                                        </th>
                                        <th>
                                            جنسیت
                                        </th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% for customer in list_customers_in_foundation_course %}
                                        <tr>
                                            <td>
                                                {{ forloop.counter }}
                                            </td>
                                            <td>
                                                <a href="{% url 'customers:customer_detail' customer.customer.id %}">
                                                    {{ customer.customer.nick_name }}
                                                </a>
                                            </td>
                                            <td>
                                                {{ customer.customer.age }}
                                            </td>
                                            <td class="project_progress">
                                                {{ customer.customer.get_gender }}
                                            </td>
                                        </tr>
                                    {% endfor %}

                                    </tbody>
                                </table>
                            </div>
                            <!-- /.card-body -->
                        </div>
                    </section>
                </div>

                <div class="row">
                    <section class="content col-lg-12">
                        <div class="card">
                            <div class="card-header">
                                <h3 class="card-title" style="float: right">
                                    لیست بیماران دوره درمانی
                                </h3>

                                <div class="card-tools" style="float: left">
                                    <button type="button" class="btn btn-tool" data-card-widget="collapse"
                                            data-toggle="tooltip" title="Collapse">
                                        <i class="fas fa-minus"></i></button>
                                    <button type="button" class="btn btn-tool" data-card-widget="remove"
                                            data-toggle="tooltip" title="Remove">
                                        <i class="fas fa-times"></i></button>
                                </div>
                            </div>

                            <div class="card-body p-0" style="display: block;">
                                <table class="table table-striped projects">
                                    <thead>
                                    <tr>
                                        <th style="width: 1%">
                                            #
                                        </th>
                                        <th style="width: 20%">
                                            نام مستعار
                                        </th>
                                        <th style="width: 30%">
                                            سن
                                        </th>
                                        <th>
                                            جنسیت
                                        </th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% for customer in list_customers_in_healing_period %}
                                        <tr>
                                            <td>
                                                {{ forloop.counter }}
                                            </td>
                                            <td>
                                                <a href="{% url 'customers:customer_detail' customer.customer.id %}">
                                                    {{ customer.customer.nick_name }}
                                                </a>
                                            </td>
                                            <td>
                                                {{ customer.customer.age }}
                                            </td>
                                            <td class="project_progress">
                                                {{ customer.customer.get_gender }}
                                            </td>
                                        </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                            <!-- /.card-body -->
                        </div>

                    </section>

                </div>

                <div class="row">
                    <section class="content col-lg-12">
                        <div class="card">
                            <div class="card-header">
                                <h3 class="card-title" style="float: right">لیست بیماران دوره فالوآپ</h3>

                                <div class="card-tools" style="float: left">
                                    <button type="button" class="btn btn-tool" data-card-widget="collapse"
                                            data-toggle="tooltip" title="Collapse">
                                        <i class="fas fa-minus"></i></button>
                                    <button type="button" class="btn btn-tool" data-card-widget="remove"
                                            data-toggle="tooltip" title="Remove">
                                        <i class="fas fa-times"></i></button>
                                </div>
                            </div>

                            <div class="card-body p-0" style="display: block;">
                                <table class="table table-striped projects">
                                    <thead>
                                    <tr>
                                        <th style="width: 1%">
                                            #
                                        </th>
                                        <th style="width: 20%">
                                            نام مستعار
                                        </th>
                                        <th style="width: 30%">
                                            سن
                                        </th>
                                        <th>
                                            جنسیت
                                        </th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% for customer in list_customers_in_follow_up %}
                                        <tr>
                                            <td>
                                                {{ forloop.counter }}
                                            </td>
                                            <td>
                                                <a href="{% url 'customers:customer_detail' customer.customer.id %}">
                                                    {{ customer.customer.nick_name }}
                                                </a>
                                            </td>
                                            <td>
                                                {{ customer.customer.age }}
                                            </td>
                                            <td class="project_progress">
                                                {{ customer.customer.get_gender_display }}
                                            </td>
                                        </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                            <!-- /.card-body -->
                        </div>

                    </section>

                </div>
            </div>
        </section>
    </div>

{% endblock %}

templates/page_404.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

	<title>404 HTML Template by Colorlib</title>

	<!-- Google font -->
	<link href="https://fonts.googleapis.com/css?family=Cabin:400,700" rel="stylesheet">

	<!-- Custom stlylesheet -->
	<link type="text/css" rel="stylesheet" href="{% static 'dist/css/error_404.css' %}" />

	<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
	<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
	<!--[if lt IE 9]>
		  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
		  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
		<![endif]-->

</head>

<body>

	<div id="notfound">
		<div class="notfound">
			<div class="notfound-404">
				<div></div>
				<h1>404</h1>
			</div>
			<h2>Page not found</h2>
			<p>The page you are looking for might have been removed had its name changed or is temporarily unavailable.</p>
			<a href="#">home page</a>
		</div>
	</div>

</body><!-- This templates was made by Colorlib (https://colorlib.com) -->

</html>

templates/rules_site.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>قوانین سامانه</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Font Awesome -->
    <link rel="stylesheet" href="{% static "plugins/fontawesome-free/css/all.min.css" %}">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- icheck bootstrap -->
    <link rel="stylesheet" href="{% static "plugins/icheck-bootstrap/icheck-bootstrap.min.css" %}">
    <!-- Theme style -->
    <link rel="stylesheet" href="{% static "dist/css/adminlte.min.css" %}">
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>
<body class="hold-transition login-page">
<div class="login-box">
    <div class="login-logo">
        <b>Ptup قوانین سامانه</b>
    </div>
    <!-- /.login-logo -->
    <div class="card">
        <div class="card-body login-card-body">
            <div class="list-group">
                {% for rule in list_rules %}
                    <a href="" class="list-group-item list-group-item-action" style="text-align: end; font-size: 20px">
                        {{ rule.rule }}</a>
                {% endfor %}

            </div>

            <p class="mb-1 mt-3">
                <button class="btn btn-outline-primary" style="float: right" onclick="goBack()">بازگشت</button>
                <br>
            </p>
        </div>
    </div>
</div>
{% if messages %}
    {% for message in messages %}
        <div class="col-3" style="position: absolute; right: 10px; top: 10px; z-index:90000;">
            <div {% if message.tags %}class="alert alert-{{ message.tags }} alert-dismissible"{% endif %}>
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true"
                        style="position: absolute;left: 0;right: auto;">X
                </button>
                {{ message }}
            </div>
        </div>
    {% endfor %}
{% endif %}

<!-- jQuery -->
<script src="{% static "plugins/jquery/jquery.min.js" %}"></script>
<!-- Bootstrap 4 -->
<script src="{% static "plugins/bootstrap/js/bootstrap.bundle.min.js" %}"></script>

<script>
    function goBack() {
        // Go back to the previous page
        window.history.back();
    }
</script>

</body>
</html>