Ptup/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views
from ptup_utilities.views import RulesSite

handler404 = 'accounts.views.handler404'

urlpatterns = [
    path('admin/', admin.site.urls),

    path('header', views.header, name="header"),
    path('footer', views.footer, name="footer"),

    path('', views.home, name="home"),
    path('site_rules/', RulesSite.as_view(), name="site_rules"),

    # apps
    path('accounts/', include("accounts.urls")),
    path('customers/', include("customers.urls")),
    path('doctors/', include("doctors.urls")),
    path('messages/', include("ptup_messages.urls")),
    path('illness/', include("illness.urls")),
    path('content/', include("healing_content.urls")),
    path('foundation_course/', include("foundation_course.urls")),
    path('followup/', include("followup.urls")),
    path('guide/', include("guide.urls")),

    # PWA
    path('', include('pwa.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.login_page, name='login'),
    path('register/customer/', views.register_page_customer, name='register_customer'),
    path('register/doctor/', views.register_page_doctor, name='register_doctor'),
    path('confirm_otp/', views.ConfirmOtpCodeView.as_view(), name='confirm_otp'),
    path('re_send_otp/', views.ReSendOtpCodeView.as_view(), name='re_send_otp'),
    path('logout/', views.log_out, name='logout'),
    #
    path('confirm_doctor/', views.ConfirmationDoctorByStaff.as_view(), name='confirm_doctor'),
    # Forgot Password
    path('forgot_password/', views.ForgotPasswordView.as_view(), name='forgot_password'),
    path('confirm_forgot_password/', views.ConfirmForgotPasswordView.as_view(), name='confirm_forgot_password'),
    path('change_password/', views.ChangePasswordView.as_view(), name='change_password'),
]

customers/urls.py
from django.urls import path
from . import views

app_name = 'customers'

urlpatterns = [
    path('completion_information_customer/', views.CompletionInformationCostumer.as_view(),
         name='completion_information_customer'),

    path('filter_customer/', views.FilterCustomer.as_view(), name="filter_customer"),

    path('customer/<int:customer_id>/detail/', views.CustomerInformationDetail.as_view(), name="customer_detail"),

    path('determining_customer_illness/<int:customer_id>/', views.DeterminingCustomerIllness.as_view(),
         name="determining_customer_illness"),

    path('operation_choice_illness_customer/<int:customer_id>/<int:illness_id>/',
         views.OperationChoiceIllnessCustomer.as_view(),
         name="operation_choice_illness_customer"),

    path('permission_start_treatment/', views.PermissionStartTreatmentCustomer.as_view(),
         name='permission_start_treatment'),

    # --------------------------------------------------

    path('healing_period_each_week/', views.healing_content_each_week, name='healing_period_each_week'),

    path('practices_each_week/<int:practice_each_week_id>/', views.practice_each_week,
         name='practices_each_week'),

    path('questionnaires_weekly/', views.questionnaires_weekly, name='questionnaires_weekly'),

    path('healing_content_map/', views.HealingContentMap.as_view(), name="healing_content_map"),

    path('completion_practice/', views.CompletionPractice.as_view(), name='completion_practice'),

    path('foundation_course_customer/', views.FoundationCourseCustomer.as_view(), name='foundation_course_customer'),

]

guide/urls.py
from django.urls import path
from . import views

app_name = 'system_guide'

urlpatterns = [
    path('guide/', views.GuidePageView.as_view(), name='guide')
]

ptup_messages/urls.py
from django.urls import path
from . import views

app_name = "ptup_messages"

urlpatterns = [
    path("messages/", views.MessagesView.as_view(), name='messages'),
    path("send_messages/", views.SendMessageView.as_view(), name='send_messages'),
    path("messages/detail/<int:message_id>/", views.DetailMessageView.as_view(), name='messages-detail'),
    path("messages/delete/<int:message_id>/", views.DeleteMessageView.as_view(), name='messages-delete'),

    # Notification
    path("notifications/", views.NotificationView.as_view(), name='notifications'),
]

templates/shared/Footer.html
{% load static %}

<footer class="main-footer">
    <strong>تمام حقوق مادی و معنوی این سامانه محفوظ است &copy;</strong>
    <div class="float-right d-none d-sm-inline-block">

    </div>
</footer>

<aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
</aside>

templates/shared/Header.html
{% load static %}

<!-- Navbar -->
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="/" class="nav-link">صفحه اصلی</a>
        </li>
    </ul>


    <!-- Right navbar links -->
    <ul class="navbar-nav mr-auto-navbav">
        <li class="nav-item">
            <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="{% url 'accounts:logout' %}">
                <i class="fa fa-sign-out-alt"></i>
            </a>
        </li>
    </ul>
</nav>
<!-- /.navbar -->

<!-- Main Sidebar Container -->
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="/" class="brand-link">
        <img src="{% static 'dist/img/AdminLTELogo.png' %}" alt="AdminLTE Logo"
             class="brand-image img-circle elevation-3"
             style="opacity: .8">
        <span class="brand-text font-weight-light">Ptup</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
        <!-- Sidebar user panel (optional) -->
        <div class="user-panel mt-3 pb-3 mb-3 d-flex">

            {% if user_role == 1 %}
                {% if user.doctor.get_image_profile_url %}
                    <div class="image">
                        <img src="{{ user.doctor.get_image_profile_url }}" class="img-circle elevation-2"
                             alt="User Image">
                    </div>
                {% endif %}

                <div class="info">
                    {% if user.doctor %}
                        <a href="{% url 'doctors:detail_doctor' user.doctor.id %}"
                           class="d-block">{{ user.doctor.get_full_name }}</a>
                    {% else %}
                        <a href="{% url 'doctors:completion_information_doctor' %}" class="d-block">کاربر جدید</a>
                    {% endif %}
                </div>


            {% elif user_role == 2 %}
                <div class="image">
                    <h5 class="text-white">نام مستعار : </h5>
                </div>

                <div class="info">
                    {% if user.customer.nick_name %}
                        <a href="" class="d-block">{{ user.customer.nick_name }}</a>
                    {% else %}
                        <a href="" class="d-block">کاربر جدید</a>
                    {% endif %}
                </div>

            {% endif %}
        </div>

        <!-- Sidebar Menu -->
        <nav class="mt-2">
            {% if user_role == 0 %}
                <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu"
                    data-accordion="false">
                    <li class="nav-item">
                        <a href="{% url 'accounts:confirm_doctor' %}" class="nav-link">
                            <i class="nav-icon fas fa-edit"></i>
                            <p>
                                لیست درمانگرها
                            </p>
                        </a>
                    </li>
                </ul>
            {% elif user_role == 1 %}
                <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu"
                    data-accordion="false">
                    {% if is_complete_information_doctor == False %}
                        <li class="nav-item">
                            <a href="{% url 'doctors:completion_information_doctor' %}" class="nav-link">
                                <i class="nav-icon fas fa-edit"></i>
                                <p>
                                    تکمیل اطلاعات
                                </p>
                            </a>
                        </li>
                    {% else %}
                        {% if user.doctor.is_verify %}
                            <li class="nav-item">
                                <a href="{% url 'doctors:get_identification_document_doctor' %}" class="nav-link">
                                    <i class="nav-icon fas fa-edit"></i>
                                    <p>
                                        تکمیل مدارک شناسایی
                                    </p>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="{% url 'doctors:list_customers_requested' %}" class="nav-link">
                                    <i class="nav-icon fas fa-list"></i>
                                    <p>
                                        لیست بیماران
                                    </p>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="{% url 'ptup_messages:messages' %}" class="nav-link">
                                    <i class="nav-icon fas fa-envelope-open"></i>
                                    <p>
                                        پیام ها
                                    </p>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="{% url 'ptup_messages:notifications' %}" class="nav-link">
                                    <i class="nav-icon far fa-bell"></i>
                                    <p>
                                        اعلان ها
                                    </p>
                                </a>
                            </li>
                        {% endif %}
                    {% endif %}
                    <li class="nav-item">
                        <a href="{% url 'system_guide:guide' %}" class="nav-link">
                            <i class="nav-icon far fa-map"></i>
                            <p>
                                راهنمایی سامانه
                            </p>
                        </a>
                    </li>
                </ul>
            {% else %}
                <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu"
                    data-accordion="false">


                    <li class="nav-item has-treeview menu-open">
                        <a href="#" class="nav-link active">
                            <i class="nav-icon fas fa-tachometer-alt"></i>
                            <p>
                                دوره درمان
                                <i class="right fas fa-angle-left"></i>
                            </p>
                        </a>
                        <ul class="nav nav-treeview" style="display: block;">
                            <li class="nav-item">
                                <a href="{% url 'customers:healing_period_each_week' %}" class="nav-link active">
                                    <i class="far fa-circle nav-icon"></i>
                                    <p>محتوای درمانی</p>
                                </a>
                            </li>


                            <li class="nav-item">
                                <a href="{% url 'customers:questionnaires_weekly' %}" class="nav-link">
                                    <i class="far fa-circle nav-icon"></i>
                                    <p>پرسشنامه های هفتگی</p>
                                </a>
                            </li>


                            <li class="nav-item">
                                <a href="{% url 'customers:healing_content_map' %}" class="nav-link">
                                    <i class="far fa-circle nav-icon"></i>
                                    <p>پرونده درمانی خودم</p>
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'ptup_messages:messages' %}" class="nav-link">
                            <i class="nav-icon fas fa-envelope-open"></i>
                            <p>
                                پیام ها
                            </p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'ptup_messages:notifications' %}" class="nav-link">
                            <i class="nav-icon far fa-bell"></i>
                            <p>
                                اعلان ها
                            </p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'system_guide:guide' %}" class="nav-link">
                            <i class="nav-icon far fa-map"></i>
                            <p>
                                راهنمایی سامانه
                            </p>
                        </a>
                    </li>
                </ul>
            {% endif %}
        </nav>
        <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
</aside>

templates/shared/_MainLayout.html
{% load pwa %}
{% load static %}
{% load render_partial %}


<!DOCTYPE html>
<html>
<head>
    {% progressive_web_app_meta %}

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{% block title %}{% endblock %}</title>
    {% include 'shared/_HeaderReferences.html' %}
    {% block header_ref %}{% endblock %}
</head>
<body class="hold-transition sidebar-mini layout-fixed">


<div class="wrapper">
    {% include "shared/Messages.html" %}

    {% render_partial 'header' %}

    {% block content %}{% endblock %}

    {% block script %}{% endblock %}

    {% render_partial 'footer' %}
    {% include 'shared/_FooterReferences.html' %}
    {% block footer_ref %}{% endblock %}

</div>

</body>
</html>